// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhzcodhrwtqusatfhmkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoemNvZGhyd3RxdXNhdGZobWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDgxODEsImV4cCI6MjA3MjM4NDE4MX0.x51sSg6aTBwIvGf161EVxhNC8vWsoslKMIoReU3P0Ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});